name: freetitle
description: FreeTitle Mobile App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  splashscreen:
  provider: ^4.0.1
  flutter_bloc: ^0.14.0
  firebase_core: 0.4.4+3
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.9
  firebase_auth: 0.15.5+3
  firebase_storage: ^3.1.1
  firebase_database: ^3.1.1
  firebase_dynamic_links: ^0.5.0
  cloud_firestore: 0.13.4+2
  flushbar: '1.10.2'
  google_sign_in: ^4.1.1
  email_validator: '^1.0.0'
  flutter_signin_button: ^1.0.0
  meta: ^1.1.6
  equatable: ^0.2.0
  bottom_navy_bar: ^5.2.2
  rxdart: ^0.22.0
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  flutter_screenutil: ^1.0.1
  liquid_pull_to_refresh: ^1.1.1
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+2
  flutter_speed_dial: ^1.2.5
  tuple: ^1.0.3
  webview_flutter: ^0.3.19+9
  share: ^0.6.3+6
  flappy_search_bar: 1.4.1
  algolia: 0.1.7
  image_picker: 0.6.3+4
  dash_chat: 1.0.19
  fluwx: 2.0.8+1
  flutter_staggered_grid_view: ^0.3.0
  palette_generator: 0.2.2
  badges: ^1.1.1
  pagination_view: ^0.7.0
  synchronized: ^2.2.0
  pull_to_refresh: ^1.5.8
  photo_view: ^0.9.2
  flutter_slidable: ^0.5.4
  flutter_html: ^0.11.1
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.7
  native_pdf_view: ^2.2.0
  chewie: ^0.9.10
  video_player: ^0.10.9
  flutube: ^0.8.3
  flutter_widget_from_html: ^0.3.3
  connectivity: ^0.4.8+2
  arkit_plugin: ^0.5.1
  cloud_functions: ^0.5.0
  assorted_layout_widgets: ^1.1.1
  dotted_border: ^1.0.5
  google_fonts: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.4"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/
    - assets/placeholders/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
